/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CucinaRouteImport } from './routes/cucina'
import { Route as CucinaLoginRouteImport } from './routes/cucina_.login'
import { Route as OrdineOrderIdRouteImport } from './routes/ordine.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CucinaRoute = CucinaRouteImport.update({
  id: '/cucina',
  path: '/cucina',
  getParentRoute: () => rootRouteImport,
} as any)
const CucinaLoginRoute = CucinaLoginRouteImport.update({
  id: '/cucina_/login',
  path: '/cucina/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdineOrderIdRoute = OrdineOrderIdRouteImport.update({
  id: '/ordine/$orderId',
  path: '/ordine/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/cucina/login': typeof CucinaLoginRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/cucina/login': typeof CucinaLoginRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/cucina_/login': typeof CucinaLoginRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cucina' | '/cucina/login' | '/ordine/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cucina' | '/cucina/login' | '/ordine/$orderId'
  id: '__root__' | '/' | '/cucina' | '/cucina_/login' | '/ordine/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CucinaRoute: typeof CucinaRoute
  CucinaLoginRoute: typeof CucinaLoginRoute
  OrdineOrderIdRoute: typeof OrdineOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cucina': {
      id: '/cucina'
      path: '/cucina'
      fullPath: '/cucina'
      preLoaderRoute: typeof CucinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cucina_/login': {
      id: '/cucina_/login'
      path: '/cucina/login'
      fullPath: '/cucina/login'
      preLoaderRoute: typeof CucinaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordine/$orderId': {
      id: '/ordine/$orderId'
      path: '/ordine/$orderId'
      fullPath: '/ordine/$orderId'
      preLoaderRoute: typeof OrdineOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CucinaRoute: CucinaRoute,
  CucinaLoginRoute: CucinaLoginRoute,
  OrdineOrderIdRoute: OrdineOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
