/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CucinaRouteImport } from './routes/cucina'
import { Route as OrdineOrderIdRouteImport } from './routes/ordine.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CucinaRoute = CucinaRouteImport.update({
  id: '/cucina',
  path: '/cucina',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdineOrderIdRoute = OrdineOrderIdRouteImport.update({
  id: '/ordine/$orderId',
  path: '/ordine/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cucina': typeof CucinaRoute
  '/ordine/$orderId': typeof OrdineOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cucina' | '/ordine/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cucina' | '/ordine/$orderId'
  id: '__root__' | '/' | '/cucina' | '/ordine/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CucinaRoute: typeof CucinaRoute
  OrdineOrderIdRoute: typeof OrdineOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cucina': {
      id: '/cucina'
      path: '/cucina'
      fullPath: '/cucina'
      preLoaderRoute: typeof CucinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordine/$orderId': {
      id: '/ordine/$orderId'
      path: '/ordine/$orderId'
      fullPath: '/ordine/$orderId'
      preLoaderRoute: typeof OrdineOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CucinaRoute: CucinaRoute,
  OrdineOrderIdRoute: OrdineOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
